# Generated by Django 5.1.15 on 2026-07-10 09:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora em que o registro foi removido logicamente.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome completo do membro.", max_length=255
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Foto do membro para identificacao visual no sistema.",
                        null=True,
                        upload_to="members/%Y/%m/",
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("lideranca", "Lideranca"),
                            ("pastor", "Pastor"),
                            ("membro", "Membro"),
                        ],
                        default="membro",
                        help_text="Tipo de cadastro do membro na igreja.",
                        max_length=20,
                    ),
                ),
                (
                    "classifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Classificacoes ministeriais vinculadas ao membro.",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        help_text="CPF do membro com 11 digitos, sem pontos ou traco.",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$", "Informe um CPF com 11 digitos."
                            )
                        ],
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Data de nascimento do membro.", null=True
                    ),
                ),
                (
                    "baptism_date",
                    models.DateField(
                        blank=True, help_text="Data do batismo do membro.", null=True
                    ),
                ),
                (
                    "acclamation_date",
                    models.DateField(
                        blank=True, help_text="Data da aclamacao do membro.", null=True
                    ),
                ),
                (
                    "include_in_birthday_list",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o membro deve aparecer na lista de aniversariantes.",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Masculino"), ("female", "Feminino")],
                        help_text="Sexo informado no cadastro.",
                        max_length=6,
                    ),
                ),
                (
                    "birthplace",
                    models.CharField(
                        blank=True,
                        help_text="Cidade de nascimento ou naturalidade do membro.",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Endereco de e-mail principal do membro.",
                        max_length=254,
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True, help_text="Nome do pai do membro.", max_length=255
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(
                        blank=True, help_text="Nome da mae do membro.", max_length=255
                    ),
                ),
                (
                    "spouse_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do conjuge, quando houver.",
                        max_length=255,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Solteiro(a)"),
                            ("married", "Casado(a)"),
                            ("stable_union", "Uniao estavel"),
                            ("divorced", "Divorciado(a)"),
                            ("widowed", "Viuvo(a)"),
                        ],
                        help_text="Estado civil do membro.",
                        max_length=20,
                    ),
                ),
                (
                    "marriage_date",
                    models.DateField(
                        blank=True,
                        help_text="Data do casamento, quando houver.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o cadastro do membro esta ativo no sistema.",
                    ),
                ),
                (
                    "inactive_reason",
                    models.TextField(
                        blank=True,
                        help_text="Motivo informado quando o cadastro do membro esta inativo.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que o cadastro foi criado.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da ultima atualizacao do cadastro.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="CEP do endereco residencial com 8 digitos, sem traco.",
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{8}$", "Informe um CEP com 8 digitos."
                            )
                        ],
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Pais do endereco residencial.",
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="UF do endereco residencial.",
                        max_length=2,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Cidade do endereco residencial.",
                        max_length=100,
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Logradouro do endereco residencial.",
                        max_length=255,
                    ),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True,
                        help_text="Numero do endereco residencial.",
                        max_length=30,
                    ),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        help_text="Complemento do endereco, como casa, bloco ou apartamento.",
                        max_length=255,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        help_text="Bairro do endereco residencial.",
                        max_length=255,
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        help_text="Membro ao qual este endereco pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="members.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("contact", "Contact"),
                        ],
                        help_text="Tipo do telefone, como celular, residencial, comercial ou contato.",
                        max_length=20,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Numero de telefone com DDD e somente digitos.",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{8,15}$", "Informe somente digitos no telefone."
                            )
                        ],
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do contato relacionado a este telefone, quando aplicavel.",
                        max_length=255,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se este e o telefone principal do membro.",
                    ),
                ),
                (
                    "receives_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se este telefone pode receber SMS.",
                    ),
                ),
                (
                    "has_whatsapp",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se este telefone possui WhatsApp.",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Membro ao qual este telefone pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["member__name", "kind", "number"],
            },
        ),
    ]
