# Generated by Django 5.1.15 on 2026-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phone",
            name="receives_sms",
        ),
        migrations.AddField(
            model_name="member",
            name="profession",
            field=models.CharField(
                blank=True, help_text="Profissao do membro.", max_length=255
            ),
        ),
    ]
