# Generated by Django 5.1.15 on 2026-06-16 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora em que o registro foi removido logicamente.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.DateField(
                blank=True, help_text="Data de nascimento do membro.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="birthplace",
            field=models.CharField(
                blank=True,
                help_text="Cidade de nascimento ou naturalidade do membro.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="CPF do membro no formato brasileiro.",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Data e hora em que o cadastro foi criado."
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Endereco de e-mail principal do membro.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="father_name",
            field=models.CharField(
                blank=True, help_text="Nome do pai do membro.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o cadastro do membro esta ativo no sistema.",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                blank=True, help_text="Estado civil do membro.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="marriage_date",
            field=models.DateField(
                blank=True, help_text="Data do casamento, quando houver.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_type",
            field=models.CharField(
                blank=True,
                help_text="Tipo de membro ou area principal de atuacao.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="mother_name",
            field=models.CharField(
                blank=True, help_text="Nome da mae do membro.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(
                help_text="Nome completo do membro.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="nationality",
            field=models.CharField(
                blank=True, help_text="Nacionalidade do membro.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="person_type",
            field=models.CharField(
                blank=True,
                help_text="Classificacao da pessoa, por exemplo: Pessoa, Lideranca ou Pastor.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="registration_type",
            field=models.CharField(
                blank=True,
                help_text="Tipo de cadastro informado pela igreja, por exemplo: Lideranca.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="sex",
            field=models.CharField(
                blank=True, help_text="Sexo informado no cadastro.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="spouse_name",
            field=models.CharField(
                blank=True, help_text="Nome do conjuge, quando houver.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Data e hora da ultima atualizacao do cadastro.",
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="city",
            field=models.CharField(
                blank=True, help_text="Cidade do endereco residencial.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="complement",
            field=models.CharField(
                blank=True,
                help_text="Complemento do endereco, como casa, bloco ou apartamento.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="country",
            field=models.CharField(
                blank=True, help_text="Pais do endereco residencial.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="district",
            field=models.CharField(
                blank=True, help_text="Bairro do endereco residencial.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="member",
            field=models.OneToOneField(
                help_text="Membro ao qual este endereco pertence.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="members.member",
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="postal_code",
            field=models.CharField(
                blank=True, help_text="CEP do endereco residencial.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="state",
            field=models.CharField(
                blank=True, help_text="Estado do endereco residencial.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="street",
            field=models.CharField(
                blank=True,
                help_text="Logradouro do endereco residencial.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="street_number",
            field=models.CharField(
                blank=True, help_text="Numero do endereco residencial.", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="memberphone",
            name="contact_name",
            field=models.CharField(
                blank=True,
                help_text="Nome do contato relacionado a este telefone, quando aplicavel.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="memberphone",
            name="has_whatsapp",
            field=models.BooleanField(
                default=False, help_text="Indica se este telefone possui WhatsApp."
            ),
        ),
        migrations.AlterField(
            model_name="memberphone",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Indica se este e o telefone principal do membro.",
            ),
        ),
        migrations.AlterField(
            model_name="memberphone",
            name="kind",
            field=models.CharField(
                choices=[
                    ("mobile", "Mobile"),
                    ("home", "Home"),
                    ("work", "Work"),
                    ("contact", "Contact"),
                ],
                help_text="Tipo do telefone, como celular, residencial, comercial ou contato.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="memberphone",
            name="member",
            field=models.ForeignKey(
                help_text="Membro ao qual este telefone pertence.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="members.member",
            ),
        ),
        migrations.AlterField(
            model_name="memberphone",
            name="number",
            field=models.CharField(help_text="Numero de telefone.", max_length=30),
        ),
        migrations.AlterField(
            model_name="memberphone",
            name="receives_sms",
            field=models.BooleanField(
                default=False, help_text="Indica se este telefone pode receber SMS."
            ),
        ),
    ]
