# Generated by Django 5.1.15 on 2026-07-10 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_phone_receives_sms_member_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade do endereço residencial.', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, help_text='Complemento do endereço, como casa, bloco ou apartamento.', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, help_text='País do endereço residencial.', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, help_text='Bairro do endereço residencial.', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='member',
            field=models.OneToOneField(help_text='Membro ao qual este endereço pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='members.member'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, help_text='CEP do endereço residencial com 8 dígitos, sem traço.', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe um CEP com 8 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, help_text='UF do endereço residencial.', max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, help_text='Logradouro do endereço residencial.', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, help_text='Número do endereço residencial.', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='acclamation_date',
            field=models.DateField(blank=True, help_text='Data da aclamação do membro.', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='classifications',
            field=models.JSONField(blank=True, default=list, help_text='Classificações ministeriais vinculadas ao membro.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do membro com 11 dígitos, sem pontos ou traço.', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Informe um CPF com 11 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, help_text='Endereço de e-mail principal do membro.', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='inactive_reason',
            field=models.TextField(blank=True, help_text='Motivo informado quando o cadastro do membro está inativo.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o cadastro do membro está ativo no sistema.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('stable_union', 'União estável'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viúvo(a)')], help_text='Estado civil do membro.', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='mother_name',
            field=models.CharField(blank=True, help_text='Nome da mãe do membro.', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto do membro para identificação visual no sistema.', null=True, upload_to='members/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, help_text='Profissão do membro.', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_type',
            field=models.CharField(choices=[('lideranca', 'Liderança'), ('pastor', 'Pastor'), ('membro', 'Membro')], default='membro', help_text='Tipo de cadastro do membro na igreja.', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, help_text='Nome do cônjuge, quando houver.', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do cadastro.'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Nome do contato relacionado a este telefone, quando aplicável.', max_length=255),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Indica se este é o telefone principal do membro.'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='kind',
            field=models.CharField(choices=[('mobile', 'Celular'), ('home', 'Residencial'), ('work', 'Comercial'), ('contact', 'Contato')], help_text='Tipo do telefone, como celular, residencial, comercial ou contato.', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(help_text='Número de telefone com DDD e somente dígitos.', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{8,15}$', 'Informe somente dígitos no telefone.')]),
        ),
    ]
