# Generated by Django 5.1.15 on 2026-06-17 10:42

import re

import django.core.validators
from django.db import migrations, models


def only_digits(value):
    """Return only numeric characters from an existing database value."""
    return re.sub(r"\D", "", value or "")


def normalize_member_fields(apps, schema_editor):
    """Normalize existing member data before stricter field definitions."""
    member_model = apps.get_model("members", "Member")
    address_model = apps.get_model("members", "MemberAddress")
    phone_model = apps.get_model("members", "MemberPhone")

    sex_values = {
        "m": "male",
        "male": "male",
        "masculino": "male",
        "f": "female",
        "female": "female",
        "feminino": "female",
    }
    marital_status_values = {
        "single": "single",
        "solteiro": "single",
        "solteira": "single",
        "married": "married",
        "casado": "married",
        "casada": "married",
        "stable_union": "stable_union",
        "uniao estavel": "stable_union",
        "união estável": "stable_union",
        "divorced": "divorced",
        "divorciado": "divorced",
        "divorciada": "divorced",
        "widowed": "widowed",
        "viuvo": "widowed",
        "viuva": "widowed",
        "viúvo": "widowed",
        "viúva": "widowed",
    }
    state_values = {
        "acre": "AC",
        "alagoas": "AL",
        "amapa": "AP",
        "amapá": "AP",
        "amazonas": "AM",
        "bahia": "BA",
        "ceara": "CE",
        "ceará": "CE",
        "distrito federal": "DF",
        "espirito santo": "ES",
        "espírito santo": "ES",
        "goias": "GO",
        "goiás": "GO",
        "maranhao": "MA",
        "maranhão": "MA",
        "mato grosso": "MT",
        "mato grosso do sul": "MS",
        "minas gerais": "MG",
        "para": "PA",
        "pará": "PA",
        "paraiba": "PB",
        "paraíba": "PB",
        "parana": "PR",
        "paraná": "PR",
        "pernambuco": "PE",
        "piaui": "PI",
        "piauí": "PI",
        "rio de janeiro": "RJ",
        "rio grande do norte": "RN",
        "rio grande do sul": "RS",
        "rondonia": "RO",
        "rondônia": "RO",
        "roraima": "RR",
        "santa catarina": "SC",
        "sao paulo": "SP",
        "são paulo": "SP",
        "sergipe": "SE",
        "tocantins": "TO",
    }

    seen_cpfs = set()
    for member in member_model.objects.order_by("pk"):
        cpf = only_digits(member.cpf)
        member.cpf = cpf if len(cpf) == 11 and cpf not in seen_cpfs else None
        if member.cpf:
            seen_cpfs.add(member.cpf)

        member.sex = sex_values.get((member.sex or "").strip().lower(), "")
        member.marital_status = marital_status_values.get(
            (member.marital_status or "").strip().lower(),
            "",
        )
        member.save(update_fields=["cpf", "sex", "marital_status"])

    for address in address_model.objects.all():
        postal_code = only_digits(address.postal_code)
        state = (address.state or "").strip()
        state_key = state.lower()

        address.postal_code = postal_code if len(postal_code) == 8 else ""
        address.state = state.upper() if len(state) == 2 else state_values.get(state_key, "")
        address.save(update_fields=["postal_code", "state"])

    for phone in phone_model.objects.all():
        number = only_digits(phone.number)
        phone.number = number[:15]
        phone.save(update_fields=["number"])


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_deleted_at_alter_member_birth_date_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_member_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="member",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="CPF do membro com 11 digitos, sem pontos ou traco.",
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$", "Informe um CPF com 11 digitos."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Solteiro(a)"),
                    ("married", "Casado(a)"),
                    ("stable_union", "Uniao estavel"),
                    ("divorced", "Divorciado(a)"),
                    ("widowed", "Viuvo(a)"),
                ],
                help_text="Estado civil do membro.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Masculino"), ("female", "Feminino")],
                help_text="Sexo informado no cadastro.",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="CEP do endereco residencial com 8 digitos, sem traco.",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "Informe um CEP com 8 digitos."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="memberaddress",
            name="state",
            field=models.CharField(
                blank=True, help_text="UF do endereco residencial.", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="memberphone",
            name="number",
            field=models.CharField(
                help_text="Numero de telefone com DDD e somente digitos.",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8,15}$", "Informe somente digitos no telefone."
                    )
                ],
            ),
        ),
    ]
