# Generated by Django 5.1.15 on 2026-07-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_address_city_alter_address_complement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
