# Generated by Django 5.1.15 on 2026-06-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_member_cpf_alter_member_marital_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MemberAddress",
            new_name="Address",
        ),
        migrations.RenameModel(
            old_name="MemberPhone",
            new_name="Phone",
        ),
    ]
