# Generated by Django 5.1.15 on 2026-07-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_rename_memberaddress_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="include_in_birthday_list",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o membro deve aparecer na lista de aniversariantes.",
            ),
        ),
    ]
