# Generated by Django 5.1.15 on 2026-07-31 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_remove_address_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Telefone do membro com DDD e somente dígitos.",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8,15}$", "Informe somente dígitos no telefone."
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Phone",
        ),
    ]
