# Generated by Django 5.1.15 on 2026-07-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_member_include_in_birthday_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="member_type",
        ),
        migrations.AddField(
            model_name="member",
            name="acclamation_date",
            field=models.DateField(
                blank=True, help_text="Data da aclamacao do membro.", null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="baptism_date",
            field=models.DateField(
                blank=True, help_text="Data do batismo do membro.", null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="inactive_reason",
            field=models.TextField(
                blank=True,
                help_text="Motivo informado quando o cadastro do membro esta inativo.",
            ),
        ),
    ]
