# Generated by Django 5.1.15 on 2026-07-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_remove_member_member_type_member_acclamation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Foto do membro para identificacao visual no sistema.",
                null=True,
                upload_to="members/%Y/%m/",
            ),
        ),
    ]
