# Generated by Django 5.1.15 on 2026-07-09 18:21

import unicodedata

from django.db import migrations, models


def normalize_registration_type(apps, schema_editor):
    """Convert existing registration types to the new required choices."""
    member = apps.get_model("members", "Member")
    values_by_normalized_text = {
        "lideranca": "lideranca",
        "pastor": "pastor",
        "membro": "membro",
    }

    for item in member.objects.all().only("pk", "registration_type"):
        normalized_text = unicodedata.normalize(
            "NFKD",
            item.registration_type or "",
        )
        normalized_text = normalized_text.encode("ascii", "ignore").decode("ascii")
        normalized_text = normalized_text.strip().lower()
        item.registration_type = values_by_normalized_text.get(normalized_text, "membro")
        item.save(update_fields=["registration_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_member_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="member",
            name="person_type",
        ),
        migrations.AddField(
            model_name="member",
            name="classifications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Classificacoes ministeriais vinculadas ao membro.",
            ),
        ),
        migrations.RunPython(normalize_registration_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="member",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("lideranca", "Lideranca"),
                    ("pastor", "Pastor"),
                    ("membro", "Membro"),
                ],
                default="membro",
                help_text="Tipo de cadastro do membro na igreja.",
                max_length=20,
            ),
        ),
    ]
