# Generated by Django 5.1.15 on 2026-07-22 18:45

import apps.birthdays.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BirthdayReportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o envio automático de aniversariantes está ativo.",
                    ),
                ),
                (
                    "week_starts_on",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        default=0,
                        help_text="Dia considerado como início da semana de aniversariantes.",
                    ),
                ),
                (
                    "send_day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        default=0,
                        help_text="Dia da semana em que o e-mail deve ser enviado.",
                    ),
                ),
                (
                    "send_time",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="Horário local em que o e-mail deve ser enviado.",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de destinatários do relatório semanal.",
                        validators=[apps.birthdays.models.validate_email_list],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que a configuração foi criada.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização da configuração.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Birthday report setting",
                "verbose_name_plural": "Birthday report settings",
            },
        ),
        migrations.CreateModel(
            name="BirthdayReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="Data inicial do período contemplado no relatório."
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="Data final do período contemplado no relatório."
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem JPEG gerada para o relatório.",
                        null=True,
                        upload_to=apps.birthdays.models.birthday_report_upload_to,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que o relatório foi gerado.",
                    ),
                ),
                (
                    "send_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviado com sucesso"),
                            ("failed", "Falhou"),
                            ("no_birthdays", "Sem aniversariantes"),
                        ],
                        default="pending",
                        help_text="Status do envio de e-mail do relatório.",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da última tentativa de envio do relatório.",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem segura com detalhes úteis da falha, quando houver.",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Destinatários usados no envio deste relatório.",
                        validators=[apps.birthdays.models.validate_email_list],
                    ),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade de membros presentes no relatório.",
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True,
                        help_text="Assunto do e-mail enviado para este relatório.",
                        max_length=255,
                    ),
                ),
                (
                    "is_automatic",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o relatório foi criado pelo processamento automático.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do relatório.",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["-generated_at"], name="birthday_report_generated_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_automatic", True)),
                        fields=("period_start", "period_end"),
                        name="unique_automatic_birthday_report_period",
                    )
                ],
            },
        ),
    ]
