# Generated by Django 5.1.15 on 2026-07-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("birthdays", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="birthdayreportsettings",
            name="send_time",
        ),
    ]
